from screens import ViewBrandBySubCat,Settings,LoginScreen,ViewEmployeeInfo,ViewBrandSubCategoryWithOption,ViewCustomerById,BillScreen,AddEmployeeInfo,DeleteAndUpdateEmployeeDetails,ViewCustomerByContact, ViewItemById,ViewItemByName,ViewSupplierByName,ViewSupplierByGst,ViewSupplierByContact,ViewSupplierById,AddBrandsScreen,AddCategoryScreen,AddUser,AddCustomers,ViewCustomerInfo,DeleteAndUpdateCustomer,ViewBrands,ViewCategory,DeleteAndUpdateBrands,DeleteAndUpdateCategory,DeleteBrandSubCategory,AddSubCategoryScreen,ViewSubCategory,AddBrandSubcategoryScreen,ViewBrandSubCategory,DeleteAndUpdateSubCategory,AddItemInfoScreen,ViewItemInfo,DeleteAndUpdateItem,AddSupplierScreen,ViewSupplier,DeleteAndUpdateSupplier,AddSupplierBrandInfo,ViewSupplierBrandInfo,DeleteSupplierBrandInfo,AddStockInfo
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *


if __name__=='__main__':
    app=QApplication(sys.argv)
    #ex = DeleteAndUpdateEmployeeDetails.DeleteAndUpdateEmployeeDetails()
    #ex=AddBrandsScreen.AddBrandsScreen()
    #ex = AddCategoryScreen.AddCategoryScreen()
    #ex = AddCustomers.AddCustomers()
    #ex = ViewCustomerInfo.ViewCustomerInfo()
    #ex = DeleteAndUpdateCustomer.DeleteAndUpdateCustomer()
    #ex = AddUser.AddUser()
    #ex = ViewBrands.ViewBrands()
    #ex = ViewCategory.ViewCategory()
    #ex = DeleteAndUpdateBrands.DeleteAndUpdateBrands()
    #ex = DeleteAndUpdateCategory.DeleteAndUpdateCategory()
    #ex = AddSupplierScreen.AddSupplierScreen()
    #ex=ViewSupplier.ViewSupplier()
    #ex=DeleteAndUpdateSupplier.DeleteAndUpdateSupplier()
    #ex = AddSubCategoryScreen.AddSubCategoryScreen()
    #ex = ViewSubCategory.ViewSubCategory()
    #ex = DeleteAndUpdateSubCategory.DeleteAndUpdateSubCategory()
    #ex = AddBrandSubcategoryScreen.AddBrandSubCategoryScreen()
    #ex = ViewBrandSubCategory.ViewBrandSubCategory()
    #ex = DeleteBrandSubCategory.DeleteBrandSubCategory()
    #ex = AddItemInfoScreen.AddItemInfoScreen()
    #ex = ViewItemInfo.ViewItemInfo()
    #ex = DeleteAndUpdateItem.DeleteAndUpdateItem()
    #ex = AddSupplierBrandInfo.AddSupplierBrandInfo()
    #ex = ViewSupplierBrandInfo.ViewSupplierBrandInfo()
    #ex = DeleteSupplierBrandInfo.DeleteSupplierBrandInfo()
    #ex = AddStockInfo.AddStockInfo()
    #ex = ViewItemById.ViewItemById()
    #ex = ViewItemByName.ViewItemByName()
    #ex = ViewSupplierByName.ViewSupplierByName()
    #ex = ViewSupplierById.ViewSupplierById()
    #ex = ViewSupplierByContact.ViewSupplierByContact()
    #ex = ViewSupplierByGst.ViewSupplierByGst()
    #ex = ViewCustomerById.ViewCustomerById()
    #ex = ViewCustomerByContact.ViewCustomerByContact()
    ex = BillScreen.BillScreen()
    #ex = AddEmployeeInfo.AddEmployeeInfo()
    #ex = DeleteAndUpdateEmployeeDetails.DeleteAndUpdateEmployeeDetails()
    #ex=ViewEmployeeInfo.ViewEmployeeInfo()
    #ex = ViewBrandBySubCat.ViewBrandBySubCat()
    #ex = LoginScreen.LoginScreen()
    #ex=Settings.Settings()

    #ex = ViewBrandSubCategoryWithOption.ViewBrandSubCategoryWithOption()

    sys.exit(app.exec_())